version: '2'
services:
  web:
    build:
      context: .      
    command: bundle exec puma -p 9292 -e production
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo_production
    ports:
      - 9292:9292
    links:
      - mongodb:mongodb

  mongodb:
    image: mongo:3.2
    command: mongod --smallfiles
